name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: test   # 👈 build seulement si tests OK

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t flaskapp .

  notify-failure:
    name: Send email if tests fail
    needs: test
    if: always() && needs.test.result == 'failure'
    runs-on: ubuntu-latest

    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v16
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "GitHub Actions - Test failure"
          to: samarmokkedem@gmail.com
          from: ${{ secrets.MAIL_USERNAME }}
          body: |
            Les tests ont échoué dans le projet FlaskApp.

            Dépôt : ${{ github.repository }}
            Branche : ${{ github.ref_name }}
            Workflow : ${{ github.workflow }}

            Voir le run :
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}